// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/gyselroth/balloon-sdk-go/client/ballon_app_elasticsearch_v2"
	"github.com/gyselroth/balloon-sdk-go/client/convert_v2"
	"github.com/gyselroth/balloon-sdk-go/client/core_v2"
	"github.com/gyselroth/balloon-sdk-go/client/desktopclient_v2"
	"github.com/gyselroth/balloon-sdk-go/client/notification_v2"
	"github.com/gyselroth/balloon-sdk-go/client/preview_v2"
	"github.com/gyselroth/balloon-sdk-go/client/sharelink_v2"
	"github.com/gyselroth/balloon-sdk-go/client/wopi_v2"
)

// Default balloon HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new balloon HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Balloon {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new balloon HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Balloon {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new balloon client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Balloon {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Balloon)
	cli.Transport = transport

	cli.BallonAppElasticsearchV2 = ballon_app_elasticsearch_v2.New(transport, formats)

	cli.ConvertV2 = convert_v2.New(transport, formats)

	cli.CoreV2 = core_v2.New(transport, formats)

	cli.DesktopclientV2 = desktopclient_v2.New(transport, formats)

	cli.NotificationV2 = notification_v2.New(transport, formats)

	cli.PreviewV2 = preview_v2.New(transport, formats)

	cli.SharelinkV2 = sharelink_v2.New(transport, formats)

	cli.WopiV2 = wopi_v2.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Balloon is a client for balloon
type Balloon struct {
	BallonAppElasticsearchV2 *ballon_app_elasticsearch_v2.Client

	ConvertV2 *convert_v2.Client

	CoreV2 *core_v2.Client

	DesktopclientV2 *desktopclient_v2.Client

	NotificationV2 *notification_v2.Client

	PreviewV2 *preview_v2.Client

	SharelinkV2 *sharelink_v2.Client

	WopiV2 *wopi_v2.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Balloon) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.BallonAppElasticsearchV2.SetTransport(transport)

	c.ConvertV2.SetTransport(transport)

	c.CoreV2.SetTransport(transport)

	c.DesktopclientV2.SetTransport(transport)

	c.NotificationV2.SetTransport(transport)

	c.PreviewV2.SetTransport(transport)

	c.SharelinkV2.SetTransport(transport)

	c.WopiV2.SetTransport(transport)

}
