// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetNodesReader is a Reader for the GetNodes structure.
type GetNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetNodesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetNodesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNodesOK creates a GetNodesOK with default headers values
func NewGetNodesOK() *GetNodesOK {
	return &GetNodesOK{}
}

/*GetNodesOK handles this case with default header values.

List of nodes
*/
type GetNodesOK struct {
	Payload *models.CoreV2Nodes
}

func (o *GetNodesOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesOK  %+v", 200, o.Payload)
}

func (o *GetNodesOK) GetPayload() *models.CoreV2Nodes {
	return o.Payload
}

func (o *GetNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Nodes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesForbidden creates a GetNodesForbidden with default headers values
func NewGetNodesForbidden() *GetNodesForbidden {
	return &GetNodesForbidden{}
}

/*GetNodesForbidden handles this case with default header values.

Access denied
*/
type GetNodesForbidden struct {
}

func (o *GetNodesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesForbidden ", 403)
}

func (o *GetNodesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetNodesNotFound creates a GetNodesNotFound with default headers values
func NewGetNodesNotFound() *GetNodesNotFound {
	return &GetNodesNotFound{}
}

/*GetNodesNotFound handles this case with default header values.

Resource does not exists
*/
type GetNodesNotFound struct {
}

func (o *GetNodesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesNotFound ", 404)
}

func (o *GetNodesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
