// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChildrenParams creates a new GetChildrenParams object
// with the default values initialized.
func NewGetChildrenParams() *GetChildrenParams {
	var (
		recursiveDefault = bool(false)
	)
	return &GetChildrenParams{
		Recursive: &recursiveDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChildrenParamsWithTimeout creates a new GetChildrenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChildrenParamsWithTimeout(timeout time.Duration) *GetChildrenParams {
	var (
		recursiveDefault = bool(false)
	)
	return &GetChildrenParams{
		Recursive: &recursiveDefault,

		timeout: timeout,
	}
}

// NewGetChildrenParamsWithContext creates a new GetChildrenParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChildrenParamsWithContext(ctx context.Context) *GetChildrenParams {
	var (
		recursiveDefault = bool(false)
	)
	return &GetChildrenParams{
		Recursive: &recursiveDefault,

		Context: ctx,
	}
}

// NewGetChildrenParamsWithHTTPClient creates a new GetChildrenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChildrenParamsWithHTTPClient(client *http.Client) *GetChildrenParams {
	var (
		recursiveDefault = bool(false)
	)
	return &GetChildrenParams{
		Recursive:  &recursiveDefault,
		HTTPClient: client,
	}
}

/*GetChildrenParams contains all the parameters to send to the API endpoint
for the get children operation typically these are written to a http.Request
*/
type GetChildrenParams struct {

	/*Attributes
	  Filter attributes

	*/
	Attributes []string
	/*Collection
	  Parent collection

	*/
	Collection string
	/*Deleted
	  Wheter to include deleted or not

	*/
	Deleted *int64
	/*Limit
	  Objects limit, per default 20 objects will get returned

	*/
	Limit *int64
	/*Offset
	  Objects offset, per default it starts from 0. You may also request a negative offset which will return results from the end [total - offset].

	*/
	Offset *int64
	/*Query
	  Specify a MongoDB based resource query (https://docs.mongodb.com/manual/tutorial/query-documents) using JSON (For example: {"name": {$regex: 'foo.*'}}).

	*/
	Query *string
	/*Recursive
	  Include children recursively.

	*/
	Recursive *bool
	/*Sort
	  Specify a MongoDB sort operation (https://docs.mongodb.com/manual/reference/method/cursor.sort/) using JSON (For example: {"name": -1}).

	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get children params
func (o *GetChildrenParams) WithTimeout(timeout time.Duration) *GetChildrenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get children params
func (o *GetChildrenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get children params
func (o *GetChildrenParams) WithContext(ctx context.Context) *GetChildrenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get children params
func (o *GetChildrenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get children params
func (o *GetChildrenParams) WithHTTPClient(client *http.Client) *GetChildrenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get children params
func (o *GetChildrenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributes adds the attributes to the get children params
func (o *GetChildrenParams) WithAttributes(attributes []string) *GetChildrenParams {
	o.SetAttributes(attributes)
	return o
}

// SetAttributes adds the attributes to the get children params
func (o *GetChildrenParams) SetAttributes(attributes []string) {
	o.Attributes = attributes
}

// WithCollection adds the collection to the get children params
func (o *GetChildrenParams) WithCollection(collection string) *GetChildrenParams {
	o.SetCollection(collection)
	return o
}

// SetCollection adds the collection to the get children params
func (o *GetChildrenParams) SetCollection(collection string) {
	o.Collection = collection
}

// WithDeleted adds the deleted to the get children params
func (o *GetChildrenParams) WithDeleted(deleted *int64) *GetChildrenParams {
	o.SetDeleted(deleted)
	return o
}

// SetDeleted adds the deleted to the get children params
func (o *GetChildrenParams) SetDeleted(deleted *int64) {
	o.Deleted = deleted
}

// WithLimit adds the limit to the get children params
func (o *GetChildrenParams) WithLimit(limit *int64) *GetChildrenParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get children params
func (o *GetChildrenParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get children params
func (o *GetChildrenParams) WithOffset(offset *int64) *GetChildrenParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get children params
func (o *GetChildrenParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithQuery adds the query to the get children params
func (o *GetChildrenParams) WithQuery(query *string) *GetChildrenParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the get children params
func (o *GetChildrenParams) SetQuery(query *string) {
	o.Query = query
}

// WithRecursive adds the recursive to the get children params
func (o *GetChildrenParams) WithRecursive(recursive *bool) *GetChildrenParams {
	o.SetRecursive(recursive)
	return o
}

// SetRecursive adds the recursive to the get children params
func (o *GetChildrenParams) SetRecursive(recursive *bool) {
	o.Recursive = recursive
}

// WithSort adds the sort to the get children params
func (o *GetChildrenParams) WithSort(sort *string) *GetChildrenParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get children params
func (o *GetChildrenParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetChildrenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesAttributes := o.Attributes

	joinedAttributes := swag.JoinByFormat(valuesAttributes, "")
	// query array param attributes
	if err := r.SetQueryParam("attributes", joinedAttributes...); err != nil {
		return err
	}

	// path param collection
	if err := r.SetPathParam("collection", o.Collection); err != nil {
		return err
	}

	if o.Deleted != nil {

		// query param deleted
		var qrDeleted int64
		if o.Deleted != nil {
			qrDeleted = *o.Deleted
		}
		qDeleted := swag.FormatInt64(qrDeleted)
		if qDeleted != "" {
			if err := r.SetQueryParam("deleted", qDeleted); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Query != nil {

		// query param query
		var qrQuery string
		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {
			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}

	}

	if o.Recursive != nil {

		// query param recursive
		var qrRecursive bool
		if o.Recursive != nil {
			qrRecursive = *o.Recursive
		}
		qRecursive := swag.FormatBool(qrRecursive)
		if qRecursive != "" {
			if err := r.SetQueryParam("recursive", qRecursive); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
