// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetGroupMembersReader is a Reader for the GetGroupMembers structure.
type GetGroupMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetGroupMembersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGroupMembersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupMembersOK creates a GetGroupMembersOK with default headers values
func NewGetGroupMembersOK() *GetGroupMembersOK {
	return &GetGroupMembersOK{}
}

/*GetGroupMembersOK handles this case with default header values.

List of users
*/
type GetGroupMembersOK struct {
	Payload *models.CoreV2Users
}

func (o *GetGroupMembersOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}/members][%d] getGroupMembersOK  %+v", 200, o.Payload)
}

func (o *GetGroupMembersOK) GetPayload() *models.CoreV2Users {
	return o.Payload
}

func (o *GetGroupMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Users)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupMembersForbidden creates a GetGroupMembersForbidden with default headers values
func NewGetGroupMembersForbidden() *GetGroupMembersForbidden {
	return &GetGroupMembersForbidden{}
}

/*GetGroupMembersForbidden handles this case with default header values.

Access denied
*/
type GetGroupMembersForbidden struct {
}

func (o *GetGroupMembersForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}/members][%d] getGroupMembersForbidden ", 403)
}

func (o *GetGroupMembersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetGroupMembersNotFound creates a GetGroupMembersNotFound with default headers values
func NewGetGroupMembersNotFound() *GetGroupMembersNotFound {
	return &GetGroupMembersNotFound{}
}

/*GetGroupMembersNotFound handles this case with default header values.

Resource does not exists
*/
type GetGroupMembersNotFound struct {
}

func (o *GetGroupMembersNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}/members][%d] getGroupMembersNotFound ", 404)
}

func (o *GetGroupMembersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
