// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetDeltaReader is a Reader for the GetDelta structure.
type GetDeltaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeltaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeltaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetDeltaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDeltaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDeltaOK creates a GetDeltaOK with default headers values
func NewGetDeltaOK() *GetDeltaOK {
	return &GetDeltaOK{}
}

/*GetDeltaOK handles this case with default header values.

Delta
*/
type GetDeltaOK struct {
	Payload *models.CoreV2Delta
}

func (o *GetDeltaOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes/delta][%d] getDeltaOK  %+v", 200, o.Payload)
}

func (o *GetDeltaOK) GetPayload() *models.CoreV2Delta {
	return o.Payload
}

func (o *GetDeltaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Delta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeltaForbidden creates a GetDeltaForbidden with default headers values
func NewGetDeltaForbidden() *GetDeltaForbidden {
	return &GetDeltaForbidden{}
}

/*GetDeltaForbidden handles this case with default header values.

Access denied
*/
type GetDeltaForbidden struct {
}

func (o *GetDeltaForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes/delta][%d] getDeltaForbidden ", 403)
}

func (o *GetDeltaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeltaNotFound creates a GetDeltaNotFound with default headers values
func NewGetDeltaNotFound() *GetDeltaNotFound {
	return &GetDeltaNotFound{}
}

/*GetDeltaNotFound handles this case with default header values.

Resource does not exists
*/
type GetDeltaNotFound struct {
}

func (o *GetDeltaNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes/delta][%d] getDeltaNotFound ", 404)
}

func (o *GetDeltaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
