// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetRootChildrenReader is a Reader for the GetRootChildren structure.
type GetRootChildrenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRootChildrenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRootChildrenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetRootChildrenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRootChildrenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRootChildrenOK creates a GetRootChildrenOK with default headers values
func NewGetRootChildrenOK() *GetRootChildrenOK {
	return &GetRootChildrenOK{}
}

/*GetRootChildrenOK handles this case with default header values.

List of children
*/
type GetRootChildrenOK struct {
	Payload *models.CoreV2Nodes
}

func (o *GetRootChildrenOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections/children][%d] getRootChildrenOK  %+v", 200, o.Payload)
}

func (o *GetRootChildrenOK) GetPayload() *models.CoreV2Nodes {
	return o.Payload
}

func (o *GetRootChildrenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Nodes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRootChildrenForbidden creates a GetRootChildrenForbidden with default headers values
func NewGetRootChildrenForbidden() *GetRootChildrenForbidden {
	return &GetRootChildrenForbidden{}
}

/*GetRootChildrenForbidden handles this case with default header values.

Access denied
*/
type GetRootChildrenForbidden struct {
}

func (o *GetRootChildrenForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections/children][%d] getRootChildrenForbidden ", 403)
}

func (o *GetRootChildrenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRootChildrenNotFound creates a GetRootChildrenNotFound with default headers values
func NewGetRootChildrenNotFound() *GetRootChildrenNotFound {
	return &GetRootChildrenNotFound{}
}

/*GetRootChildrenNotFound handles this case with default header values.

Resource does not exists
*/
type GetRootChildrenNotFound struct {
}

func (o *GetRootChildrenNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/collections/children][%d] getRootChildrenNotFound ", 404)
}

func (o *GetRootChildrenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
