// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetGroupReader is a Reader for the GetGroup structure.
type GetGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetGroupUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGroupOK creates a GetGroupOK with default headers values
func NewGetGroupOK() *GetGroupOK {
	return &GetGroupOK{}
}

/*GetGroupOK handles this case with default header values.

Group
*/
type GetGroupOK struct {
	Payload *models.CoreV2Group
}

func (o *GetGroupOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}][%d] getGroupOK  %+v", 200, o.Payload)
}

func (o *GetGroupOK) GetPayload() *models.CoreV2Group {
	return o.Payload
}

func (o *GetGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupBadRequest creates a GetGroupBadRequest with default headers values
func NewGetGroupBadRequest() *GetGroupBadRequest {
	return &GetGroupBadRequest{}
}

/*GetGroupBadRequest handles this case with default header values.

Bad Reqeust
*/
type GetGroupBadRequest struct {
	Payload *models.CoreV2Error
}

func (o *GetGroupBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}][%d] getGroupBadRequest  %+v", 400, o.Payload)
}

func (o *GetGroupBadRequest) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupUnauthorized creates a GetGroupUnauthorized with default headers values
func NewGetGroupUnauthorized() *GetGroupUnauthorized {
	return &GetGroupUnauthorized{}
}

/*GetGroupUnauthorized handles this case with default header values.

Unauthorized
*/
type GetGroupUnauthorized struct {
	Payload *models.CoreV2Error
}

func (o *GetGroupUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}][%d] getGroupUnauthorized  %+v", 401, o.Payload)
}

func (o *GetGroupUnauthorized) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupForbidden creates a GetGroupForbidden with default headers values
func NewGetGroupForbidden() *GetGroupForbidden {
	return &GetGroupForbidden{}
}

/*GetGroupForbidden handles this case with default header values.

Forbidden
*/
type GetGroupForbidden struct {
	Payload *models.CoreV2Error
}

func (o *GetGroupForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}][%d] getGroupForbidden  %+v", 403, o.Payload)
}

func (o *GetGroupForbidden) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupNotFound creates a GetGroupNotFound with default headers values
func NewGetGroupNotFound() *GetGroupNotFound {
	return &GetGroupNotFound{}
}

/*GetGroupNotFound handles this case with default header values.

The specified resource was not found
*/
type GetGroupNotFound struct {
	Payload *models.CoreV2Error
}

func (o *GetGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}][%d] getGroupNotFound  %+v", 404, o.Payload)
}

func (o *GetGroupNotFound) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupUnprocessableEntity creates a GetGroupUnprocessableEntity with default headers values
func NewGetGroupUnprocessableEntity() *GetGroupUnprocessableEntity {
	return &GetGroupUnprocessableEntity{}
}

/*GetGroupUnprocessableEntity handles this case with default header values.

Unauthorized
*/
type GetGroupUnprocessableEntity struct {
	Payload *models.CoreV2Error
}

func (o *GetGroupUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}][%d] getGroupUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *GetGroupUnprocessableEntity) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetGroupUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGroupInternalServerError creates a GetGroupInternalServerError with default headers values
func NewGetGroupInternalServerError() *GetGroupInternalServerError {
	return &GetGroupInternalServerError{}
}

/*GetGroupInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetGroupInternalServerError struct {
	Payload *models.CoreV2Error
}

func (o *GetGroupInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/groups/{group}][%d] getGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *GetGroupInternalServerError) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
