// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNodesParams creates a new GetNodesParams object
// with the default values initialized.
func NewGetNodesParams() *GetNodesParams {
	var ()
	return &GetNodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNodesParamsWithTimeout creates a new GetNodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNodesParamsWithTimeout(timeout time.Duration) *GetNodesParams {
	var ()
	return &GetNodesParams{

		timeout: timeout,
	}
}

// NewGetNodesParamsWithContext creates a new GetNodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNodesParamsWithContext(ctx context.Context) *GetNodesParams {
	var ()
	return &GetNodesParams{

		Context: ctx,
	}
}

// NewGetNodesParamsWithHTTPClient creates a new GetNodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNodesParamsWithHTTPClient(client *http.Client) *GetNodesParams {
	var ()
	return &GetNodesParams{
		HTTPClient: client,
	}
}

/*GetNodesParams contains all the parameters to send to the API endpoint
for the get nodes operation typically these are written to a http.Request
*/
type GetNodesParams struct {

	/*Attributes
	  Filter attributes

	*/
	Attributes []string
	/*Deleted
	  Wheter to include deleted or not

	*/
	Deleted *float64
	/*Limit
	  Objects limit, per default 20 objects will get returned

	*/
	Limit *float64
	/*Offset
	  Objects offset, per default it starts from 0. You may also request a negative offset which will return results from the end [total - offset].

	*/
	Offset *float64
	/*Query
	  Specify a MongoDB based resource query (https://docs.mongodb.com/manual/tutorial/query-documents) using JSON (For example: {"name": {$regex: 'foo.*'}}).

	*/
	Query *string
	/*Sort
	  Specify a MongoDB sort operation (https://docs.mongodb.com/manual/reference/method/cursor.sort/) using JSON (For example: {"name": -1}).

	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get nodes params
func (o *GetNodesParams) WithTimeout(timeout time.Duration) *GetNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get nodes params
func (o *GetNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get nodes params
func (o *GetNodesParams) WithContext(ctx context.Context) *GetNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get nodes params
func (o *GetNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get nodes params
func (o *GetNodesParams) WithHTTPClient(client *http.Client) *GetNodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get nodes params
func (o *GetNodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributes adds the attributes to the get nodes params
func (o *GetNodesParams) WithAttributes(attributes []string) *GetNodesParams {
	o.SetAttributes(attributes)
	return o
}

// SetAttributes adds the attributes to the get nodes params
func (o *GetNodesParams) SetAttributes(attributes []string) {
	o.Attributes = attributes
}

// WithDeleted adds the deleted to the get nodes params
func (o *GetNodesParams) WithDeleted(deleted *float64) *GetNodesParams {
	o.SetDeleted(deleted)
	return o
}

// SetDeleted adds the deleted to the get nodes params
func (o *GetNodesParams) SetDeleted(deleted *float64) {
	o.Deleted = deleted
}

// WithLimit adds the limit to the get nodes params
func (o *GetNodesParams) WithLimit(limit *float64) *GetNodesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get nodes params
func (o *GetNodesParams) SetLimit(limit *float64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get nodes params
func (o *GetNodesParams) WithOffset(offset *float64) *GetNodesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get nodes params
func (o *GetNodesParams) SetOffset(offset *float64) {
	o.Offset = offset
}

// WithQuery adds the query to the get nodes params
func (o *GetNodesParams) WithQuery(query *string) *GetNodesParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the get nodes params
func (o *GetNodesParams) SetQuery(query *string) {
	o.Query = query
}

// WithSort adds the sort to the get nodes params
func (o *GetNodesParams) WithSort(sort *string) *GetNodesParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get nodes params
func (o *GetNodesParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesAttributes := o.Attributes

	joinedAttributes := swag.JoinByFormat(valuesAttributes, "")
	// query array param attributes
	if err := r.SetQueryParam("attributes", joinedAttributes...); err != nil {
		return err
	}

	if o.Deleted != nil {

		// query param deleted
		var qrDeleted float64
		if o.Deleted != nil {
			qrDeleted = *o.Deleted
		}
		qDeleted := swag.FormatFloat64(qrDeleted)
		if qDeleted != "" {
			if err := r.SetQueryParam("deleted", qDeleted); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit float64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatFloat64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset float64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatFloat64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Query != nil {

		// query param query
		var qrQuery string
		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {
			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
