// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetParentNodesParams creates a new GetParentNodesParams object
// with the default values initialized.
func NewGetParentNodesParams() *GetParentNodesParams {
	var ()
	return &GetParentNodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetParentNodesParamsWithTimeout creates a new GetParentNodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetParentNodesParamsWithTimeout(timeout time.Duration) *GetParentNodesParams {
	var ()
	return &GetParentNodesParams{

		timeout: timeout,
	}
}

// NewGetParentNodesParamsWithContext creates a new GetParentNodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetParentNodesParamsWithContext(ctx context.Context) *GetParentNodesParams {
	var ()
	return &GetParentNodesParams{

		Context: ctx,
	}
}

// NewGetParentNodesParamsWithHTTPClient creates a new GetParentNodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetParentNodesParamsWithHTTPClient(client *http.Client) *GetParentNodesParams {
	var ()
	return &GetParentNodesParams{
		HTTPClient: client,
	}
}

/*GetParentNodesParams contains all the parameters to send to the API endpoint
for the get parent nodes operation typically these are written to a http.Request
*/
type GetParentNodesParams struct {

	/*Attributes
	  Filter attributes

	*/
	Attributes []string
	/*Node
	  Node identifier

	*/
	Node string
	/*Self
	  Include requested collection itself at the end of the list (Will be ignored if the requested node is a file)

	*/
	Self *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get parent nodes params
func (o *GetParentNodesParams) WithTimeout(timeout time.Duration) *GetParentNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get parent nodes params
func (o *GetParentNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get parent nodes params
func (o *GetParentNodesParams) WithContext(ctx context.Context) *GetParentNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get parent nodes params
func (o *GetParentNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get parent nodes params
func (o *GetParentNodesParams) WithHTTPClient(client *http.Client) *GetParentNodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get parent nodes params
func (o *GetParentNodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributes adds the attributes to the get parent nodes params
func (o *GetParentNodesParams) WithAttributes(attributes []string) *GetParentNodesParams {
	o.SetAttributes(attributes)
	return o
}

// SetAttributes adds the attributes to the get parent nodes params
func (o *GetParentNodesParams) SetAttributes(attributes []string) {
	o.Attributes = attributes
}

// WithNode adds the node to the get parent nodes params
func (o *GetParentNodesParams) WithNode(node string) *GetParentNodesParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the get parent nodes params
func (o *GetParentNodesParams) SetNode(node string) {
	o.Node = node
}

// WithSelf adds the self to the get parent nodes params
func (o *GetParentNodesParams) WithSelf(self *bool) *GetParentNodesParams {
	o.SetSelf(self)
	return o
}

// SetSelf adds the self to the get parent nodes params
func (o *GetParentNodesParams) SetSelf(self *bool) {
	o.Self = self
}

// WriteToRequest writes these params to a swagger request
func (o *GetParentNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesAttributes := o.Attributes

	joinedAttributes := swag.JoinByFormat(valuesAttributes, "")
	// query array param attributes
	if err := r.SetQueryParam("attributes", joinedAttributes...); err != nil {
		return err
	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	if o.Self != nil {

		// query param self
		var qrSelf bool
		if o.Self != nil {
			qrSelf = *o.Self
		}
		qSelf := swag.FormatBool(qrSelf)
		if qSelf != "" {
			if err := r.SetQueryParam("self", qSelf); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
