// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetNodesReader is a Reader for the GetNodes structure.
type GetNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetNodesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetNodesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetNodesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetNodesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetNodesUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNodesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNodesOK creates a GetNodesOK with default headers values
func NewGetNodesOK() *GetNodesOK {
	return &GetNodesOK{}
}

/*GetNodesOK handles this case with default header values.

List of nodes
*/
type GetNodesOK struct {
	Payload *models.CoreV2Nodes
}

func (o *GetNodesOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesOK  %+v", 200, o.Payload)
}

func (o *GetNodesOK) GetPayload() *models.CoreV2Nodes {
	return o.Payload
}

func (o *GetNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Nodes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesBadRequest creates a GetNodesBadRequest with default headers values
func NewGetNodesBadRequest() *GetNodesBadRequest {
	return &GetNodesBadRequest{}
}

/*GetNodesBadRequest handles this case with default header values.

Bad Reqeust
*/
type GetNodesBadRequest struct {
	Payload *models.CoreV2Error
}

func (o *GetNodesBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesBadRequest  %+v", 400, o.Payload)
}

func (o *GetNodesBadRequest) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetNodesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesUnauthorized creates a GetNodesUnauthorized with default headers values
func NewGetNodesUnauthorized() *GetNodesUnauthorized {
	return &GetNodesUnauthorized{}
}

/*GetNodesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetNodesUnauthorized struct {
	Payload *models.CoreV2Error
}

func (o *GetNodesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesUnauthorized  %+v", 401, o.Payload)
}

func (o *GetNodesUnauthorized) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetNodesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesForbidden creates a GetNodesForbidden with default headers values
func NewGetNodesForbidden() *GetNodesForbidden {
	return &GetNodesForbidden{}
}

/*GetNodesForbidden handles this case with default header values.

Forbidden
*/
type GetNodesForbidden struct {
	Payload *models.CoreV2Error
}

func (o *GetNodesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesForbidden  %+v", 403, o.Payload)
}

func (o *GetNodesForbidden) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetNodesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesNotFound creates a GetNodesNotFound with default headers values
func NewGetNodesNotFound() *GetNodesNotFound {
	return &GetNodesNotFound{}
}

/*GetNodesNotFound handles this case with default header values.

The specified resource was not found
*/
type GetNodesNotFound struct {
	Payload *models.CoreV2Error
}

func (o *GetNodesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesNotFound  %+v", 404, o.Payload)
}

func (o *GetNodesNotFound) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetNodesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesUnprocessableEntity creates a GetNodesUnprocessableEntity with default headers values
func NewGetNodesUnprocessableEntity() *GetNodesUnprocessableEntity {
	return &GetNodesUnprocessableEntity{}
}

/*GetNodesUnprocessableEntity handles this case with default header values.

Unauthorized
*/
type GetNodesUnprocessableEntity struct {
	Payload *models.CoreV2Error
}

func (o *GetNodesUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *GetNodesUnprocessableEntity) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetNodesUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNodesInternalServerError creates a GetNodesInternalServerError with default headers values
func NewGetNodesInternalServerError() *GetNodesInternalServerError {
	return &GetNodesInternalServerError{}
}

/*GetNodesInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetNodesInternalServerError struct {
	Payload *models.CoreV2Error
}

func (o *GetNodesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/nodes][%d] getNodesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetNodesInternalServerError) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *GetNodesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
