// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetFileHistoryReader is a Reader for the GetFileHistory structure.
type GetFileHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFileHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFileHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetFileHistoryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetFileHistoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFileHistoryOK creates a GetFileHistoryOK with default headers values
func NewGetFileHistoryOK() *GetFileHistoryOK {
	return &GetFileHistoryOK{}
}

/*GetFileHistoryOK handles this case with default header values.

File history
*/
type GetFileHistoryOK struct {
	Payload *models.CoreV2FileHistory
}

func (o *GetFileHistoryOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/history][%d] getFileHistoryOK  %+v", 200, o.Payload)
}

func (o *GetFileHistoryOK) GetPayload() *models.CoreV2FileHistory {
	return o.Payload
}

func (o *GetFileHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2FileHistory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFileHistoryForbidden creates a GetFileHistoryForbidden with default headers values
func NewGetFileHistoryForbidden() *GetFileHistoryForbidden {
	return &GetFileHistoryForbidden{}
}

/*GetFileHistoryForbidden handles this case with default header values.

Access denied
*/
type GetFileHistoryForbidden struct {
}

func (o *GetFileHistoryForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/history][%d] getFileHistoryForbidden ", 403)
}

func (o *GetFileHistoryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFileHistoryNotFound creates a GetFileHistoryNotFound with default headers values
func NewGetFileHistoryNotFound() *GetFileHistoryNotFound {
	return &GetFileHistoryNotFound{}
}

/*GetFileHistoryNotFound handles this case with default header values.

Resource does not exists
*/
type GetFileHistoryNotFound struct {
}

func (o *GetFileHistoryNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/history][%d] getFileHistoryNotFound ", 404)
}

func (o *GetFileHistoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
