// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// RollbackFileReader is a Reader for the RollbackFile structure.
type RollbackFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RollbackFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRollbackFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewRollbackFileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRollbackFileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRollbackFileOK creates a RollbackFileOK with default headers values
func NewRollbackFileOK() *RollbackFileOK {
	return &RollbackFileOK{}
}

/*RollbackFileOK handles this case with default header values.

File
*/
type RollbackFileOK struct {
	Payload *models.CoreV2File
}

func (o *RollbackFileOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/files/{file}/restore][%d] rollbackFileOK  %+v", 200, o.Payload)
}

func (o *RollbackFileOK) GetPayload() *models.CoreV2File {
	return o.Payload
}

func (o *RollbackFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2File)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRollbackFileForbidden creates a RollbackFileForbidden with default headers values
func NewRollbackFileForbidden() *RollbackFileForbidden {
	return &RollbackFileForbidden{}
}

/*RollbackFileForbidden handles this case with default header values.

Access denied
*/
type RollbackFileForbidden struct {
}

func (o *RollbackFileForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/files/{file}/restore][%d] rollbackFileForbidden ", 403)
}

func (o *RollbackFileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRollbackFileNotFound creates a RollbackFileNotFound with default headers values
func NewRollbackFileNotFound() *RollbackFileNotFound {
	return &RollbackFileNotFound{}
}

/*RollbackFileNotFound handles this case with default header values.

Resource does not exists
*/
type RollbackFileNotFound struct {
}

func (o *RollbackFileNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/files/{file}/restore][%d] rollbackFileNotFound ", 404)
}

func (o *RollbackFileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
