// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUndeleteGroupParams creates a new UndeleteGroupParams object
// with the default values initialized.
func NewUndeleteGroupParams() *UndeleteGroupParams {
	var ()
	return &UndeleteGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUndeleteGroupParamsWithTimeout creates a new UndeleteGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUndeleteGroupParamsWithTimeout(timeout time.Duration) *UndeleteGroupParams {
	var ()
	return &UndeleteGroupParams{

		timeout: timeout,
	}
}

// NewUndeleteGroupParamsWithContext creates a new UndeleteGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewUndeleteGroupParamsWithContext(ctx context.Context) *UndeleteGroupParams {
	var ()
	return &UndeleteGroupParams{

		Context: ctx,
	}
}

// NewUndeleteGroupParamsWithHTTPClient creates a new UndeleteGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUndeleteGroupParamsWithHTTPClient(client *http.Client) *UndeleteGroupParams {
	var ()
	return &UndeleteGroupParams{
		HTTPClient: client,
	}
}

/*UndeleteGroupParams contains all the parameters to send to the API endpoint
for the undelete group operation typically these are written to a http.Request
*/
type UndeleteGroupParams struct {

	/*Group
	  Resource identifier

	*/
	Group string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the undelete group params
func (o *UndeleteGroupParams) WithTimeout(timeout time.Duration) *UndeleteGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the undelete group params
func (o *UndeleteGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the undelete group params
func (o *UndeleteGroupParams) WithContext(ctx context.Context) *UndeleteGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the undelete group params
func (o *UndeleteGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the undelete group params
func (o *UndeleteGroupParams) WithHTTPClient(client *http.Client) *UndeleteGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the undelete group params
func (o *UndeleteGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the undelete group params
func (o *UndeleteGroupParams) WithGroup(group string) *UndeleteGroupParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the undelete group params
func (o *UndeleteGroupParams) SetGroup(group string) {
	o.Group = group
}

// WriteToRequest writes these params to a swagger request
func (o *UndeleteGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group
	if err := r.SetPathParam("group", o.Group); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
