// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUndeleteNodeParams creates a new UndeleteNodeParams object
// with the default values initialized.
func NewUndeleteNodeParams() *UndeleteNodeParams {
	var (
		conflictDefault = float64(0)
		moveDefault     = bool(false)
	)
	return &UndeleteNodeParams{
		Conflict: &conflictDefault,
		Move:     &moveDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUndeleteNodeParamsWithTimeout creates a new UndeleteNodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUndeleteNodeParamsWithTimeout(timeout time.Duration) *UndeleteNodeParams {
	var (
		conflictDefault = float64(0)
		moveDefault     = bool(false)
	)
	return &UndeleteNodeParams{
		Conflict: &conflictDefault,
		Move:     &moveDefault,

		timeout: timeout,
	}
}

// NewUndeleteNodeParamsWithContext creates a new UndeleteNodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewUndeleteNodeParamsWithContext(ctx context.Context) *UndeleteNodeParams {
	var (
		conflictDefault = float64(0)
		moveDefault     = bool(false)
	)
	return &UndeleteNodeParams{
		Conflict: &conflictDefault,
		Move:     &moveDefault,

		Context: ctx,
	}
}

// NewUndeleteNodeParamsWithHTTPClient creates a new UndeleteNodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUndeleteNodeParamsWithHTTPClient(client *http.Client) *UndeleteNodeParams {
	var (
		conflictDefault = float64(0)
		moveDefault     = bool(false)
	)
	return &UndeleteNodeParams{
		Conflict:   &conflictDefault,
		Move:       &moveDefault,
		HTTPClient: client,
	}
}

/*UndeleteNodeParams contains all the parameters to send to the API endpoint
for the undelete node operation typically these are written to a http.Request
*/
type UndeleteNodeParams struct {

	/*Conflict
	  Conflict resolution

	*/
	Conflict *float64
	/*Destid
	  If node should also be moved during undelete

	*/
	Destid *string
	/*Move
	  If node should also be moved during undelete

	*/
	Move *bool
	/*Node
	  Node identifier

	*/
	Node string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the undelete node params
func (o *UndeleteNodeParams) WithTimeout(timeout time.Duration) *UndeleteNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the undelete node params
func (o *UndeleteNodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the undelete node params
func (o *UndeleteNodeParams) WithContext(ctx context.Context) *UndeleteNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the undelete node params
func (o *UndeleteNodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the undelete node params
func (o *UndeleteNodeParams) WithHTTPClient(client *http.Client) *UndeleteNodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the undelete node params
func (o *UndeleteNodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConflict adds the conflict to the undelete node params
func (o *UndeleteNodeParams) WithConflict(conflict *float64) *UndeleteNodeParams {
	o.SetConflict(conflict)
	return o
}

// SetConflict adds the conflict to the undelete node params
func (o *UndeleteNodeParams) SetConflict(conflict *float64) {
	o.Conflict = conflict
}

// WithDestid adds the destid to the undelete node params
func (o *UndeleteNodeParams) WithDestid(destid *string) *UndeleteNodeParams {
	o.SetDestid(destid)
	return o
}

// SetDestid adds the destid to the undelete node params
func (o *UndeleteNodeParams) SetDestid(destid *string) {
	o.Destid = destid
}

// WithMove adds the move to the undelete node params
func (o *UndeleteNodeParams) WithMove(move *bool) *UndeleteNodeParams {
	o.SetMove(move)
	return o
}

// SetMove adds the move to the undelete node params
func (o *UndeleteNodeParams) SetMove(move *bool) {
	o.Move = move
}

// WithNode adds the node to the undelete node params
func (o *UndeleteNodeParams) WithNode(node string) *UndeleteNodeParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the undelete node params
func (o *UndeleteNodeParams) SetNode(node string) {
	o.Node = node
}

// WriteToRequest writes these params to a swagger request
func (o *UndeleteNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Conflict != nil {

		// query param conflict
		var qrConflict float64
		if o.Conflict != nil {
			qrConflict = *o.Conflict
		}
		qConflict := swag.FormatFloat64(qrConflict)
		if qConflict != "" {
			if err := r.SetQueryParam("conflict", qConflict); err != nil {
				return err
			}
		}

	}

	if o.Destid != nil {

		// query param destid
		var qrDestid string
		if o.Destid != nil {
			qrDestid = *o.Destid
		}
		qDestid := qrDestid
		if qDestid != "" {
			if err := r.SetQueryParam("destid", qDestid); err != nil {
				return err
			}
		}

	}

	if o.Move != nil {

		// query param move
		var qrMove bool
		if o.Move != nil {
			qrMove = *o.Move
		}
		qMove := swag.FormatBool(qrMove)
		if qMove != "" {
			if err := r.SetQueryParam("move", qMove); err != nil {
				return err
			}
		}

	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
