// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// UndeleteGroupReader is a Reader for the UndeleteGroup structure.
type UndeleteGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UndeleteGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUndeleteGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewUndeleteGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUndeleteGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUndeleteGroupOK creates a UndeleteGroupOK with default headers values
func NewUndeleteGroupOK() *UndeleteGroupOK {
	return &UndeleteGroupOK{}
}

/*UndeleteGroupOK handles this case with default header values.

Group
*/
type UndeleteGroupOK struct {
	Payload *models.CoreV2Group
}

func (o *UndeleteGroupOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/groups/{group}/undelete][%d] undeleteGroupOK  %+v", 200, o.Payload)
}

func (o *UndeleteGroupOK) GetPayload() *models.CoreV2Group {
	return o.Payload
}

func (o *UndeleteGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUndeleteGroupForbidden creates a UndeleteGroupForbidden with default headers values
func NewUndeleteGroupForbidden() *UndeleteGroupForbidden {
	return &UndeleteGroupForbidden{}
}

/*UndeleteGroupForbidden handles this case with default header values.

Access denied
*/
type UndeleteGroupForbidden struct {
}

func (o *UndeleteGroupForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/groups/{group}/undelete][%d] undeleteGroupForbidden ", 403)
}

func (o *UndeleteGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUndeleteGroupNotFound creates a UndeleteGroupNotFound with default headers values
func NewUndeleteGroupNotFound() *UndeleteGroupNotFound {
	return &UndeleteGroupNotFound{}
}

/*UndeleteGroupNotFound handles this case with default header values.

Resource does not exists
*/
type UndeleteGroupNotFound struct {
}

func (o *UndeleteGroupNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/groups/{group}/undelete][%d] undeleteGroupNotFound ", 404)
}

func (o *UndeleteGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
