// Code generated by go-swagger; DO NOT EDIT.

package core_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// UndeleteUserReader is a Reader for the UndeleteUser structure.
type UndeleteUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UndeleteUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUndeleteUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewUndeleteUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUndeleteUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUndeleteUserOK creates a UndeleteUserOK with default headers values
func NewUndeleteUserOK() *UndeleteUserOK {
	return &UndeleteUserOK{}
}

/*UndeleteUserOK handles this case with default header values.

User
*/
type UndeleteUserOK struct {
	Payload *models.CoreV2User
}

func (o *UndeleteUserOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/users/{user}/undelete][%d] undeleteUserOK  %+v", 200, o.Payload)
}

func (o *UndeleteUserOK) GetPayload() *models.CoreV2User {
	return o.Payload
}

func (o *UndeleteUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUndeleteUserForbidden creates a UndeleteUserForbidden with default headers values
func NewUndeleteUserForbidden() *UndeleteUserForbidden {
	return &UndeleteUserForbidden{}
}

/*UndeleteUserForbidden handles this case with default header values.

Access denied
*/
type UndeleteUserForbidden struct {
}

func (o *UndeleteUserForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/users/{user}/undelete][%d] undeleteUserForbidden ", 403)
}

func (o *UndeleteUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUndeleteUserNotFound creates a UndeleteUserNotFound with default headers values
func NewUndeleteUserNotFound() *UndeleteUserNotFound {
	return &UndeleteUserNotFound{}
}

/*UndeleteUserNotFound handles this case with default header values.

Resource does not exists
*/
type UndeleteUserNotFound struct {
}

func (o *UndeleteUserNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/users/{user}/undelete][%d] undeleteUserNotFound ", 404)
}

func (o *UndeleteUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
