// Code generated by go-swagger; DO NOT EDIT.

package convert_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetSlaveReader is a Reader for the GetSlave structure.
type GetSlaveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSlaveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSlaveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetSlaveForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSlaveNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSlaveOK creates a GetSlaveOK with default headers values
func NewGetSlaveOK() *GetSlaveOK {
	return &GetSlaveOK{}
}

/*GetSlaveOK handles this case with default header values.

Slave
*/
type GetSlaveOK struct {
	Payload *models.ConvertV2Slave
}

func (o *GetSlaveOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/convert/slaves/{slave}][%d] getSlaveOK  %+v", 200, o.Payload)
}

func (o *GetSlaveOK) GetPayload() *models.ConvertV2Slave {
	return o.Payload
}

func (o *GetSlaveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConvertV2Slave)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSlaveForbidden creates a GetSlaveForbidden with default headers values
func NewGetSlaveForbidden() *GetSlaveForbidden {
	return &GetSlaveForbidden{}
}

/*GetSlaveForbidden handles this case with default header values.

Access denied
*/
type GetSlaveForbidden struct {
}

func (o *GetSlaveForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/convert/slaves/{slave}][%d] getSlaveForbidden ", 403)
}

func (o *GetSlaveForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSlaveNotFound creates a GetSlaveNotFound with default headers values
func NewGetSlaveNotFound() *GetSlaveNotFound {
	return &GetSlaveNotFound{}
}

/*GetSlaveNotFound handles this case with default header values.

Resource does not exists
*/
type GetSlaveNotFound struct {
}

func (o *GetSlaveNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/convert/slaves/{slave}][%d] getSlaveNotFound ", 404)
}

func (o *GetSlaveNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
