// Code generated by go-swagger; DO NOT EDIT.

package convert_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// GetSlavesReader is a Reader for the GetSlaves structure.
type GetSlavesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSlavesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSlavesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetSlavesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSlavesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSlavesOK creates a GetSlavesOK with default headers values
func NewGetSlavesOK() *GetSlavesOK {
	return &GetSlavesOK{}
}

/*GetSlavesOK handles this case with default header values.

Slaves
*/
type GetSlavesOK struct {
	Payload *models.ConvertV2Slaves
}

func (o *GetSlavesOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/convert/slaves][%d] getSlavesOK  %+v", 200, o.Payload)
}

func (o *GetSlavesOK) GetPayload() *models.ConvertV2Slaves {
	return o.Payload
}

func (o *GetSlavesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConvertV2Slaves)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSlavesForbidden creates a GetSlavesForbidden with default headers values
func NewGetSlavesForbidden() *GetSlavesForbidden {
	return &GetSlavesForbidden{}
}

/*GetSlavesForbidden handles this case with default header values.

Access denied
*/
type GetSlavesForbidden struct {
}

func (o *GetSlavesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/convert/slaves][%d] getSlavesForbidden ", 403)
}

func (o *GetSlavesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSlavesNotFound creates a GetSlavesNotFound with default headers values
func NewGetSlavesNotFound() *GetSlavesNotFound {
	return &GetSlavesNotFound{}
}

/*GetSlavesNotFound handles this case with default header values.

Resource does not exists
*/
type GetSlavesNotFound struct {
}

func (o *GetSlavesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v2/files/{file}/convert/slaves][%d] getSlavesNotFound ", 404)
}

func (o *GetSlavesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
