// Code generated by go-swagger; DO NOT EDIT.

package convert_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSlavesParams creates a new GetSlavesParams object
// with the default values initialized.
func NewGetSlavesParams() *GetSlavesParams {
	var ()
	return &GetSlavesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSlavesParamsWithTimeout creates a new GetSlavesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSlavesParamsWithTimeout(timeout time.Duration) *GetSlavesParams {
	var ()
	return &GetSlavesParams{

		timeout: timeout,
	}
}

// NewGetSlavesParamsWithContext creates a new GetSlavesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSlavesParamsWithContext(ctx context.Context) *GetSlavesParams {
	var ()
	return &GetSlavesParams{

		Context: ctx,
	}
}

// NewGetSlavesParamsWithHTTPClient creates a new GetSlavesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSlavesParamsWithHTTPClient(client *http.Client) *GetSlavesParams {
	var ()
	return &GetSlavesParams{
		HTTPClient: client,
	}
}

/*GetSlavesParams contains all the parameters to send to the API endpoint
for the get slaves operation typically these are written to a http.Request
*/
type GetSlavesParams struct {

	/*File
	  File identifier

	*/
	File string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get slaves params
func (o *GetSlavesParams) WithTimeout(timeout time.Duration) *GetSlavesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get slaves params
func (o *GetSlavesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get slaves params
func (o *GetSlavesParams) WithContext(ctx context.Context) *GetSlavesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get slaves params
func (o *GetSlavesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get slaves params
func (o *GetSlavesParams) WithHTTPClient(client *http.Client) *GetSlavesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get slaves params
func (o *GetSlavesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the get slaves params
func (o *GetSlavesParams) WithFile(file string) *GetSlavesParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the get slaves params
func (o *GetSlavesParams) SetFile(file string) {
	o.File = file
}

// WriteToRequest writes these params to a swagger request
func (o *GetSlavesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param file
	if err := r.SetPathParam("file", o.File); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
