// Code generated by go-swagger; DO NOT EDIT.

package desktopclient_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDesktopClientParams creates a new GetDesktopClientParams object
// with the default values initialized.
func NewGetDesktopClientParams() *GetDesktopClientParams {
	var ()
	return &GetDesktopClientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDesktopClientParamsWithTimeout creates a new GetDesktopClientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDesktopClientParamsWithTimeout(timeout time.Duration) *GetDesktopClientParams {
	var ()
	return &GetDesktopClientParams{

		timeout: timeout,
	}
}

// NewGetDesktopClientParamsWithContext creates a new GetDesktopClientParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDesktopClientParamsWithContext(ctx context.Context) *GetDesktopClientParams {
	var ()
	return &GetDesktopClientParams{

		Context: ctx,
	}
}

// NewGetDesktopClientParamsWithHTTPClient creates a new GetDesktopClientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDesktopClientParamsWithHTTPClient(client *http.Client) *GetDesktopClientParams {
	var ()
	return &GetDesktopClientParams{
		HTTPClient: client,
	}
}

/*GetDesktopClientParams contains all the parameters to send to the API endpoint
for the get desktop client operation typically these are written to a http.Request
*/
type GetDesktopClientParams struct {

	/*Format
	  Request client foramt (deb, rpm, exe, pkg, zip or a custom format)

	*/
	Format string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get desktop client params
func (o *GetDesktopClientParams) WithTimeout(timeout time.Duration) *GetDesktopClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get desktop client params
func (o *GetDesktopClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get desktop client params
func (o *GetDesktopClientParams) WithContext(ctx context.Context) *GetDesktopClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get desktop client params
func (o *GetDesktopClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get desktop client params
func (o *GetDesktopClientParams) WithHTTPClient(client *http.Client) *GetDesktopClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get desktop client params
func (o *GetDesktopClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFormat adds the format to the get desktop client params
func (o *GetDesktopClientParams) WithFormat(format string) *GetDesktopClientParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the get desktop client params
func (o *GetDesktopClientParams) SetFormat(format string) {
	o.Format = format
}

// WriteToRequest writes these params to a swagger request
func (o *GetDesktopClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param format
	if err := r.SetPathParam("format", o.Format); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
