// Code generated by go-swagger; DO NOT EDIT.

package notification_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// DeleteNotificationReader is a Reader for the DeleteNotification structure.
type DeleteNotificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNotificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteNotificationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteNotificationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteNotificationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteNotificationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteNotificationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDeleteNotificationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteNotificationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNotificationNoContent creates a DeleteNotificationNoContent with default headers values
func NewDeleteNotificationNoContent() *DeleteNotificationNoContent {
	return &DeleteNotificationNoContent{}
}

/*DeleteNotificationNoContent handles this case with default header values.

If successful the server will respond with 204 No Content
*/
type DeleteNotificationNoContent struct {
}

func (o *DeleteNotificationNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/notifications/{notification}][%d] deleteNotificationNoContent ", 204)
}

func (o *DeleteNotificationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNotificationBadRequest creates a DeleteNotificationBadRequest with default headers values
func NewDeleteNotificationBadRequest() *DeleteNotificationBadRequest {
	return &DeleteNotificationBadRequest{}
}

/*DeleteNotificationBadRequest handles this case with default header values.

Bad Reqeust
*/
type DeleteNotificationBadRequest struct {
	Payload *models.CoreV2Error
}

func (o *DeleteNotificationBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/notifications/{notification}][%d] deleteNotificationBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteNotificationBadRequest) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *DeleteNotificationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNotificationUnauthorized creates a DeleteNotificationUnauthorized with default headers values
func NewDeleteNotificationUnauthorized() *DeleteNotificationUnauthorized {
	return &DeleteNotificationUnauthorized{}
}

/*DeleteNotificationUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteNotificationUnauthorized struct {
	Payload *models.CoreV2Error
}

func (o *DeleteNotificationUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/notifications/{notification}][%d] deleteNotificationUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteNotificationUnauthorized) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *DeleteNotificationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNotificationForbidden creates a DeleteNotificationForbidden with default headers values
func NewDeleteNotificationForbidden() *DeleteNotificationForbidden {
	return &DeleteNotificationForbidden{}
}

/*DeleteNotificationForbidden handles this case with default header values.

Forbidden
*/
type DeleteNotificationForbidden struct {
	Payload *models.CoreV2Error
}

func (o *DeleteNotificationForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/notifications/{notification}][%d] deleteNotificationForbidden  %+v", 403, o.Payload)
}

func (o *DeleteNotificationForbidden) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *DeleteNotificationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNotificationNotFound creates a DeleteNotificationNotFound with default headers values
func NewDeleteNotificationNotFound() *DeleteNotificationNotFound {
	return &DeleteNotificationNotFound{}
}

/*DeleteNotificationNotFound handles this case with default header values.

The specified resource was not found
*/
type DeleteNotificationNotFound struct {
	Payload *models.CoreV2Error
}

func (o *DeleteNotificationNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/notifications/{notification}][%d] deleteNotificationNotFound  %+v", 404, o.Payload)
}

func (o *DeleteNotificationNotFound) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *DeleteNotificationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNotificationUnprocessableEntity creates a DeleteNotificationUnprocessableEntity with default headers values
func NewDeleteNotificationUnprocessableEntity() *DeleteNotificationUnprocessableEntity {
	return &DeleteNotificationUnprocessableEntity{}
}

/*DeleteNotificationUnprocessableEntity handles this case with default header values.

Unauthorized
*/
type DeleteNotificationUnprocessableEntity struct {
	Payload *models.CoreV2Error
}

func (o *DeleteNotificationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/notifications/{notification}][%d] deleteNotificationUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *DeleteNotificationUnprocessableEntity) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *DeleteNotificationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNotificationInternalServerError creates a DeleteNotificationInternalServerError with default headers values
func NewDeleteNotificationInternalServerError() *DeleteNotificationInternalServerError {
	return &DeleteNotificationInternalServerError{}
}

/*DeleteNotificationInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteNotificationInternalServerError struct {
	Payload *models.CoreV2Error
}

func (o *DeleteNotificationInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/notifications/{notification}][%d] deleteNotificationInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteNotificationInternalServerError) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *DeleteNotificationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
