// Code generated by go-swagger; DO NOT EDIT.

package notification_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNotificationParams creates a new GetNotificationParams object
// with the default values initialized.
func NewGetNotificationParams() *GetNotificationParams {
	var ()
	return &GetNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNotificationParamsWithTimeout creates a new GetNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNotificationParamsWithTimeout(timeout time.Duration) *GetNotificationParams {
	var ()
	return &GetNotificationParams{

		timeout: timeout,
	}
}

// NewGetNotificationParamsWithContext creates a new GetNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNotificationParamsWithContext(ctx context.Context) *GetNotificationParams {
	var ()
	return &GetNotificationParams{

		Context: ctx,
	}
}

// NewGetNotificationParamsWithHTTPClient creates a new GetNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNotificationParamsWithHTTPClient(client *http.Client) *GetNotificationParams {
	var ()
	return &GetNotificationParams{
		HTTPClient: client,
	}
}

/*GetNotificationParams contains all the parameters to send to the API endpoint
for the get notification operation typically these are written to a http.Request
*/
type GetNotificationParams struct {

	/*Notification
	  Resource identifier

	*/
	Notification string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get notification params
func (o *GetNotificationParams) WithTimeout(timeout time.Duration) *GetNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get notification params
func (o *GetNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get notification params
func (o *GetNotificationParams) WithContext(ctx context.Context) *GetNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get notification params
func (o *GetNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get notification params
func (o *GetNotificationParams) WithHTTPClient(client *http.Client) *GetNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get notification params
func (o *GetNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNotification adds the notification to the get notification params
func (o *GetNotificationParams) WithNotification(notification string) *GetNotificationParams {
	o.SetNotification(notification)
	return o
}

// SetNotification adds the notification to the get notification params
func (o *GetNotificationParams) SetNotification(notification string) {
	o.Notification = notification
}

// WriteToRequest writes these params to a swagger request
func (o *GetNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param notification
	if err := r.SetPathParam("notification", o.Notification); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
