// Code generated by go-swagger; DO NOT EDIT.

package notification_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// NewSendBroadcastParams creates a new SendBroadcastParams object
// with the default values initialized.
func NewSendBroadcastParams() *SendBroadcastParams {
	var ()
	return &SendBroadcastParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendBroadcastParamsWithTimeout creates a new SendBroadcastParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendBroadcastParamsWithTimeout(timeout time.Duration) *SendBroadcastParams {
	var ()
	return &SendBroadcastParams{

		timeout: timeout,
	}
}

// NewSendBroadcastParamsWithContext creates a new SendBroadcastParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendBroadcastParamsWithContext(ctx context.Context) *SendBroadcastParams {
	var ()
	return &SendBroadcastParams{

		Context: ctx,
	}
}

// NewSendBroadcastParamsWithHTTPClient creates a new SendBroadcastParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSendBroadcastParamsWithHTTPClient(client *http.Client) *SendBroadcastParams {
	var ()
	return &SendBroadcastParams{
		HTTPClient: client,
	}
}

/*SendBroadcastParams contains all the parameters to send to the API endpoint
for the send broadcast operation typically these are written to a http.Request
*/
type SendBroadcastParams struct {

	/*Body
	  Notification

	*/
	Body *models.NotificationV2Notification

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send broadcast params
func (o *SendBroadcastParams) WithTimeout(timeout time.Duration) *SendBroadcastParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send broadcast params
func (o *SendBroadcastParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send broadcast params
func (o *SendBroadcastParams) WithContext(ctx context.Context) *SendBroadcastParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send broadcast params
func (o *SendBroadcastParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send broadcast params
func (o *SendBroadcastParams) WithHTTPClient(client *http.Client) *SendBroadcastParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send broadcast params
func (o *SendBroadcastParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the send broadcast params
func (o *SendBroadcastParams) WithBody(body *models.NotificationV2Notification) *SendBroadcastParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the send broadcast params
func (o *SendBroadcastParams) SetBody(body *models.NotificationV2Notification) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SendBroadcastParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
