// Code generated by go-swagger; DO NOT EDIT.

package wopi_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/gyselroth/balloon-sdk-go/models"
)

// CreateDocumentReader is a Reader for the CreateDocument structure.
type CreateDocumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDocumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateDocumentCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateDocumentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateDocumentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateDocumentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateDocumentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateDocumentUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateDocumentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDocumentCreated creates a CreateDocumentCreated with default headers values
func NewCreateDocumentCreated() *CreateDocumentCreated {
	return &CreateDocumentCreated{}
}

/*CreateDocumentCreated handles this case with default header values.

File
*/
type CreateDocumentCreated struct {
	Payload *models.CoreV2File
}

func (o *CreateDocumentCreated) Error() string {
	return fmt.Sprintf("[POST /api/v2/office/documents][%d] createDocumentCreated  %+v", 201, o.Payload)
}

func (o *CreateDocumentCreated) GetPayload() *models.CoreV2File {
	return o.Payload
}

func (o *CreateDocumentCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2File)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDocumentBadRequest creates a CreateDocumentBadRequest with default headers values
func NewCreateDocumentBadRequest() *CreateDocumentBadRequest {
	return &CreateDocumentBadRequest{}
}

/*CreateDocumentBadRequest handles this case with default header values.

Bad Reqeust
*/
type CreateDocumentBadRequest struct {
	Payload *models.CoreV2Error
}

func (o *CreateDocumentBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v2/office/documents][%d] createDocumentBadRequest  %+v", 400, o.Payload)
}

func (o *CreateDocumentBadRequest) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *CreateDocumentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDocumentUnauthorized creates a CreateDocumentUnauthorized with default headers values
func NewCreateDocumentUnauthorized() *CreateDocumentUnauthorized {
	return &CreateDocumentUnauthorized{}
}

/*CreateDocumentUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateDocumentUnauthorized struct {
	Payload *models.CoreV2Error
}

func (o *CreateDocumentUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v2/office/documents][%d] createDocumentUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateDocumentUnauthorized) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *CreateDocumentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDocumentForbidden creates a CreateDocumentForbidden with default headers values
func NewCreateDocumentForbidden() *CreateDocumentForbidden {
	return &CreateDocumentForbidden{}
}

/*CreateDocumentForbidden handles this case with default header values.

Forbidden
*/
type CreateDocumentForbidden struct {
	Payload *models.CoreV2Error
}

func (o *CreateDocumentForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v2/office/documents][%d] createDocumentForbidden  %+v", 403, o.Payload)
}

func (o *CreateDocumentForbidden) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *CreateDocumentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDocumentNotFound creates a CreateDocumentNotFound with default headers values
func NewCreateDocumentNotFound() *CreateDocumentNotFound {
	return &CreateDocumentNotFound{}
}

/*CreateDocumentNotFound handles this case with default header values.

The specified resource was not found
*/
type CreateDocumentNotFound struct {
	Payload *models.CoreV2Error
}

func (o *CreateDocumentNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v2/office/documents][%d] createDocumentNotFound  %+v", 404, o.Payload)
}

func (o *CreateDocumentNotFound) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *CreateDocumentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDocumentUnprocessableEntity creates a CreateDocumentUnprocessableEntity with default headers values
func NewCreateDocumentUnprocessableEntity() *CreateDocumentUnprocessableEntity {
	return &CreateDocumentUnprocessableEntity{}
}

/*CreateDocumentUnprocessableEntity handles this case with default header values.

Unauthorized
*/
type CreateDocumentUnprocessableEntity struct {
	Payload *models.CoreV2Error
}

func (o *CreateDocumentUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /api/v2/office/documents][%d] createDocumentUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateDocumentUnprocessableEntity) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *CreateDocumentUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDocumentInternalServerError creates a CreateDocumentInternalServerError with default headers values
func NewCreateDocumentInternalServerError() *CreateDocumentInternalServerError {
	return &CreateDocumentInternalServerError{}
}

/*CreateDocumentInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreateDocumentInternalServerError struct {
	Payload *models.CoreV2Error
}

func (o *CreateDocumentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v2/office/documents][%d] createDocumentInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateDocumentInternalServerError) GetPayload() *models.CoreV2Error {
	return o.Payload
}

func (o *CreateDocumentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoreV2Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
