// Code generated by go-swagger; DO NOT EDIT.

package wopi_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateWopiDocuemntContentParams creates a new UpdateWopiDocuemntContentParams object
// with the default values initialized.
func NewUpdateWopiDocuemntContentParams() *UpdateWopiDocuemntContentParams {
	var ()
	return &UpdateWopiDocuemntContentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateWopiDocuemntContentParamsWithTimeout creates a new UpdateWopiDocuemntContentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateWopiDocuemntContentParamsWithTimeout(timeout time.Duration) *UpdateWopiDocuemntContentParams {
	var ()
	return &UpdateWopiDocuemntContentParams{

		timeout: timeout,
	}
}

// NewUpdateWopiDocuemntContentParamsWithContext creates a new UpdateWopiDocuemntContentParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateWopiDocuemntContentParamsWithContext(ctx context.Context) *UpdateWopiDocuemntContentParams {
	var ()
	return &UpdateWopiDocuemntContentParams{

		Context: ctx,
	}
}

// NewUpdateWopiDocuemntContentParamsWithHTTPClient creates a new UpdateWopiDocuemntContentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateWopiDocuemntContentParamsWithHTTPClient(client *http.Client) *UpdateWopiDocuemntContentParams {
	var ()
	return &UpdateWopiDocuemntContentParams{
		HTTPClient: client,
	}
}

/*UpdateWopiDocuemntContentParams contains all the parameters to send to the API endpoint
for the update wopi docuemnt content operation typically these are written to a http.Request
*/
type UpdateWopiDocuemntContentParams struct {

	/*AccessToken
	  An access token to access the document

	*/
	AccessToken string
	/*Body
	  Document content

	*/
	Body string
	/*Document
	  The document id

	*/
	Document string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) WithTimeout(timeout time.Duration) *UpdateWopiDocuemntContentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) WithContext(ctx context.Context) *UpdateWopiDocuemntContentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) WithHTTPClient(client *http.Client) *UpdateWopiDocuemntContentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessToken adds the accessToken to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) WithAccessToken(accessToken string) *UpdateWopiDocuemntContentParams {
	o.SetAccessToken(accessToken)
	return o
}

// SetAccessToken adds the accessToken to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) SetAccessToken(accessToken string) {
	o.AccessToken = accessToken
}

// WithBody adds the body to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) WithBody(body string) *UpdateWopiDocuemntContentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) SetBody(body string) {
	o.Body = body
}

// WithDocument adds the document to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) WithDocument(document string) *UpdateWopiDocuemntContentParams {
	o.SetDocument(document)
	return o
}

// SetDocument adds the document to the update wopi docuemnt content params
func (o *UpdateWopiDocuemntContentParams) SetDocument(document string) {
	o.Document = document
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateWopiDocuemntContentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param access_token
	qrAccessToken := o.AccessToken
	qAccessToken := qrAccessToken
	if qAccessToken != "" {
		if err := r.SetQueryParam("access_token", qAccessToken); err != nil {
			return err
		}
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param document
	if err := r.SetPathParam("document", o.Document); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
