// Code generated by go-swagger; DO NOT EDIT.

package wopi_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new wopi v2 API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for wopi v2 API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateDocument Create new document from an existing office document template
*/
func (a *Client) CreateDocument(params *CreateDocumentParams) (*CreateDocumentCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateDocumentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createDocument",
		Method:             "POST",
		PathPattern:        "/api/v2/office/documents",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateDocumentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateDocumentCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createDocument: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetWopiDocument gets document session information including document owner session user and document size
*/
func (a *Client) GetWopiDocument(params *GetWopiDocumentParams) (*GetWopiDocumentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWopiDocumentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getWopiDocument",
		Method:             "GET",
		PathPattern:        "/api/v2/office/wopi/document/{document}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetWopiDocumentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetWopiDocumentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getWopiDocument: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetWopiDocumentContent gets document contents
*/
func (a *Client) GetWopiDocumentContent(params *GetWopiDocumentContentParams) (*GetWopiDocumentContentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetWopiDocumentContentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getWopiDocumentContent",
		Method:             "GET",
		PathPattern:        "/api/v2/office/wopi/document/{document}/contents",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetWopiDocumentContentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetWopiDocumentContentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getWopiDocumentContent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateWopiDocuemntContent saves document contents
*/
func (a *Client) UpdateWopiDocuemntContent(params *UpdateWopiDocuemntContentParams) (*UpdateWopiDocuemntContentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateWopiDocuemntContentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateWopiDocuemntContent",
		Method:             "POST",
		PathPattern:        "/api/v2/office/wopi/document/{document}/contents",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateWopiDocuemntContentReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateWopiDocuemntContentOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateWopiDocuemntContent: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
