// Code generated by go-swagger; DO NOT EDIT.

package sharelink_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteLinkReader is a Reader for the DeleteLink structure.
type DeleteLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteLinkNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteLinkForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteLinkNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLinkNoContent creates a DeleteLinkNoContent with default headers values
func NewDeleteLinkNoContent() *DeleteLinkNoContent {
	return &DeleteLinkNoContent{}
}

/*DeleteLinkNoContent handles this case with default header values.

The server responds with 204 if operation was successful
*/
type DeleteLinkNoContent struct {
}

func (o *DeleteLinkNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/nodes/{node}/share-link][%d] deleteLinkNoContent ", 204)
}

func (o *DeleteLinkNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLinkForbidden creates a DeleteLinkForbidden with default headers values
func NewDeleteLinkForbidden() *DeleteLinkForbidden {
	return &DeleteLinkForbidden{}
}

/*DeleteLinkForbidden handles this case with default header values.

Access denied
*/
type DeleteLinkForbidden struct {
}

func (o *DeleteLinkForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/nodes/{node}/share-link][%d] deleteLinkForbidden ", 403)
}

func (o *DeleteLinkForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLinkNotFound creates a DeleteLinkNotFound with default headers values
func NewDeleteLinkNotFound() *DeleteLinkNotFound {
	return &DeleteLinkNotFound{}
}

/*DeleteLinkNotFound handles this case with default header values.

Resource does not exists
*/
type DeleteLinkNotFound struct {
}

func (o *DeleteLinkNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/nodes/{node}/share-link][%d] deleteLinkNotFound ", 404)
}

func (o *DeleteLinkNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
