// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CoreV2JSONPatch A JSON Patch according rfc6902.
// swagger:model core.v2.JsonPatch
type CoreV2JSONPatch struct {

	// op
	Op string `json:"op,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this core v2 Json patch
func (m *CoreV2JSONPatch) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CoreV2JSONPatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CoreV2JSONPatch) UnmarshalBinary(b []byte) error {
	var res CoreV2JSONPatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
